export const local_strings = {
    en: {
        "ignore_casing": "Ignore casing",
        "words": "words",
        "characters": "characters",
        "errors": "Errors",
        "accuracy": "Accuracy",
        "start": "Start",
        "stor": "Stop",
        "light_mode": "Light mode",
        "dark_mode": "Dark mode",
        "save_score": "Save score",
        "animations": "Animations",
        "privacy_policy": "Privacy policy",
        "references": "References",
        "en_tooltip": "English",
        "sv_tooltip": "Swedish (Svenska)",
        "ru_tooltip": "Russian (Русский)",
    },

    sv: {
        "ignore_casing": "Ignorera versaler/gemener",
        "words": "ord",
        "characters": "tecken",
        "errors": "Fel",
        "accuracy": "Noggrannhet",
        "start": "Starta",
        "stor": "Avbryta",
        "light_mode": "Ljusläge",
        "dark_mode": "Mörkt läge",
        "save_score": "Spara resultat",
        "animations": "Animationer",
        "privacy_policy": "Privacy policy",
        "references": "Referenser",
        "en_tooltip": "English",
        "sv_tooltip": "Swedish (Svenska)",
        "ru_tooltip": "Russian (Русский)",
    },

    ru: {
        "ignore_casing": "Игнорировать строчные/прописные",
        "words": "слов",
        "characters": "символов",
        "errors": "Ошибки",
        "accuracy": "Точность",
        "start": "Старт",
        "stor": "Стоп",
        "light_mode": "Светлый режим",
        "dark_mode": "Темный режим",
        "save_score": "Статистика",
        "animations": "Анимации",
        "privacy_policy": "Политика конфиденциальности",
        "references": "Ссылки",
        "en_tooltip": "English",
        "sv_tooltip": "Swedish (Svenska)",
        "ru_tooltip": "Russian (Русский)",
    }
}


